#spring-related
spring:
  application:
    name: CONFIG-DEV
#resgister this service in your eureka server
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka

